apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-gen-certs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-gen-certs
        tier: security
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: kube-gen-certs
        image: andrewstuart/kube-named-zones
        imagePullPolicy: Always
        command: "/kube-gen-certs"
        args:
          - "-incluster"
          - "-suffix=astuart.co"
        resources:
          requests: &r
            cpu: 100m
            memory: 200Mi
          limits: *r
